name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t ${{secret.REGISTRY_USER}}/portfolio .
      - name: push image
        run: |
            docker login -u ${{secret.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASS}}
            docker push ${{secret.REGISTRY_USER}}/portfolio

